class Planet {
    private String name; //default is Planet
    private int size; //size are 30, 40, 50, 60 (default = 30)
    private int distance; //generated by Solar
    private int color; //1-7
    private String customColor; //hex code, is used only when color = 7

    Planet() {
        name = "Planet";
        color = 0;
        customColor = "#ffffff";
        size = 30;
    }

    //getters and setters
    String getName() {
        return name;
    }
    int getSize() {
        return (size - 20) / 10;
    }
    int getSizeReal() {
        return size;
    }
    int getDistance() {
        return distance;
    }
    int getColor() {
        return color;
    }
    String getCustomColor() { return customColor; }
    void setName(String name) {
        this.name = name;
    }
    void setSize(int size) {
        this.size = 20 + (size * 10);
    }
    void setDistance(int distance) {
        this.distance = distance;
    }
    void setColor(int color) {
        this.color = color;
    }
    void setCustomColor(String customColor) {
        this.customColor = customColor;
    }
}